### ISSUE TITLE
Peer to Peer Review

### ISSUE THREAD

**Issue by kayjeee** [akezeth/Leaderboard#4]
Hi @akezeth, very good job, it looks amazing

<img src="https://media2.giphy.com/media/5hgYDDh5oqbmE4OKJ3/giphy.gif"/>
###Highlights 

- good UI interface
- good readme file
- followed best JavaScript practices
- followed best HTML and CSS practices
- good web pack and linter setup

**Comment by akezeth** [comment]
Thank you for feedback.
